### ISSUE TITLE
[CY-2611] "Usage of last on collections" has false positives

### ISSUE THREAD

**Issue by Lasering** [codacy/codacy-scalameta#68]
### Expected Behavior
The rule "Usage of last on collections" should not report offenses in:

```scala
import fs2.Stream

val stream = Stream.emits(List(1,2,3))
stream.compile.last
```

### Actual Behavior

The [rule](https://github.com/codacy/codacy-scalameta/blob/master/patterns-base/src/main/scala/codacy/patterns/Custom_Scala_CollectionLastHead.scala) blindly checks invocations of `head`/`last`. It should also check those invocations are being performed on scala collections.

**Comment by franciscodua** [comment]
Hey @Lasering 

Unfortunately, We don't have the type information we need to check if the last method is being applied to a collection or not.
But because this is a valid (and possibly common) method name, we removed the pattern from the tool. You can find the changes here https://github.com/codacy/codacy-scalameta/pull/69.

Thanks for pointing this out
